language: cpp
install: ./gen-unix.sh
compiler:
- clang
- gcc
before_install:
	- sudo ./install-dependencies.sh
	- export WITHOUT_MARKLOGIC=1
git:
  depth: 3
os:
	- linux
	- osx
script:
	- ./build.sh && cd ./bin/test && ./mlcpptest
branches:
  only:
    - master
    - develop
		- feature-24
